import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		double average=0.0;
		double children_sum=0.0;
		int family_2=0;
		int family_3=0;
		int family_4_or_more=0;
	
	
		for(int i=0;i<T;i++)
		{
			//OneOfEach
			double x;
			int b=0;
			int g=0;
			double children=0.0;
		
			while(b<1 || g<1)
			{
				children=children+1.0;
				x=generator.nextDouble();
				if(x>=0.5) //x%2==0
				{
					b++;
				}
				else
				{
					g++;
				}
			}
			children_sum+=children;
		
			if(children==2)
			{
				family_2++;
			}
			else
			{
				if(children==3)
				{
					family_3++;
				}
				else{
					family_4_or_more++;
				}
			}

		}
		average=children_sum/T;
		System.out.println("Average: "+average+" children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: "+family_2);
		System.out.println("Number of families with 3 children: "+family_3);
		System.out.println("Number of families with 4 or more children: "+family_4_or_more);

		if(family_2>=family_3 && family_2>=family_4_or_more)
			{
				System.out.println("The most common number of children is 2.");	
			}
			else
			{
				if(family_3>=family_2 && family_3>=family_4_or_more)
				{
					System.out.println("The most common number of children is 3.");
				}
				else
				{
					System.out.println("The most common number of children is 4 or more.");
				}
			}	
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
